spring:
  # 激活开发环境配置
  profiles:
    active: prod

---
emp:
  name: ssss
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: per.zcc.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

# 为数据源用户登录信息配置秘钥
jasypt:
  encryptor:
    password: springcloud-micro-service

spring:
  profiles: dev
  application:
    name: provider-product-eureka-hystrix-config-bus-dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.130:3306/springcloud_db01?serverTimezone=GMT%2B8
    username: ENC(czInPzzwTyT20hzhyGP+uQ==)
    password: ENC(czInPzzwTyT20hzhyGP+uQ==)
    dbcp2:
      # 数据库连接池的最小维持连接数
      min-idle: 5
      # 初始化连接数
      initial-size: 5
      # 最大连接数
      max-total: 5
      # 等待连接获取的最大超时时间
      max-wait-millis: 150

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.10.130:6003/eureka/
  instance:
    # 指定实例ID,注册中心管理页面，就不会显示主机名了
    instance-id: ${spring.application.name}:${server.port}
    # 访问路径以IP地址形式显示
    prefer-ip-address: true
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: per.zcc.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

# 为数据源用户登录信息配置秘钥
jasypt:
  encryptor:
    password: springcloud-micro-service

spring:
  profiles: prod
  application:
    name: provider-product-eureka-hystrix-config-bus-prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.130:3306/springcloud_db02?serverTimezone=GMT%2B8
    username: ENC(czInPzzwTyT20hzhyGP+uQ==)
    password: ENC(czInPzzwTyT20hzhyGP+uQ==)
    dbcp2:
      # 数据库连接池的最小维持连接数
      min-idle: 5
      # 初始化连接数
      initial-size: 5
      # 最大连接数
      max-total: 5
      # 等待连接获取的最大超时时间
      max-wait-millis: 150

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.10.130:6003/eureka/
  instance:
    # 指定实例ID,注册中心管理页面，就不会显示主机名了
    instance-id: ${spring.application.name}:${server.port}
    # 访问路径以IP地址形式显示
    prefer-ip-address: true
